spring:
  application:
    name: contracts-service
  cloud:
    config:
      username: user
      password: pass
      name: contract-service
    discovery:
      enabled: false
server:
  port: 8081
  servlet:
    context-path: /contractsApi
management:
  endpoints:
    web:
      exposure:
        include: "health,metrics,info,env,liquibase,configprops"
---
spring:
  profiles: cloud
  cloud:
    discovery:
      enabled: true
# todo add cloud config uri for pcf here